from .login import Login
from .payments import Payments
from .boarder import Boarder
from .register import Register
from .room import Room
from .dashboard import Dashboard
from .db_connection import Database
from .forgot import Forgot
from .bh_info import Bh_info
